export const themes = {
  'swiss-modernist': {
    name: 'Swiss',
    bg: '#1a1a1a',
    bgAlt: '#1a1a1a',
    text: '#1a1a1a',
    textSecondary: 'rgba(26,26,26,0.5)',
    accent: '#e60012',
    accentAlt: '#1a1a1a',
    cardBg: '#ffffff',
    cardText: '#1a1a1a',
    navBg: '#1a1a1a',
    navText: '#ffffff',
    inputBorder: '#1a1a1a',
    formBg: '#ffffff',
    formText: '#1a1a1a',
    tagBg: '#1a1a1a',
    tagBorder: '#1a1a1a',
    tagText: '#ffffff',
    starBg: '#e60012',
    starText: '#ffffff',
    headingFont: "'Bebas Neue', 'Impact', sans-serif",
    bodyFont: "'Barlow', 'Helvetica Neue', sans-serif",
    fontImport:
      'https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Barlow:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,300;1,400&display=swap',
    skewAngle: '0deg',
    cardRadius: '0px',
    buttonRadius: '0px',
    cardShadow: 'none',
    bodyBg: '#ffffff',
    socialIconColor: '#1a1a1a',
    bubbleBg: '#f2f2f2',
    bubbleTextColor: '#1a1a1a',
    scanlines: false,
    typewriter: false,
    glitch: false,
    crtCurve: false,
    cardBorderStyle: '2px solid #1a1a1a',
    navBorderBottom: 'none',
    bioOverlay: 'none',
    sectionDivider: 'border-top: 2px solid #1a1a1a',
    projectLayout: 'swiss',
    headshotStyle: 'contrast',
    submitLabel: 'SUBMIT',
  },
};

export const themeKeys = Object.keys(themes);
export const defaultTheme = 'swiss-modernist';
